services:
  app:
    container_name: ${NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
    networks:
      - lan
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.entrypoints=websecure
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}.tls=true
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver
      - traefik.http.services.${NAME}.loadbalancer.server.port=3000

networks:
  web:
    external: true

  lan:
    external: false
    name: lan_${NAME}
