services:
  backend:
    container_name: ${NAME}-api
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/backend/dev.db
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./app/backend/dev.db:/app/backend/dev.db
    ports:
      - "4000:4000"
    networks:
      - lan
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}-api.rule=Host(`api.${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}-api.tls.certresolver=myresolver
      - traefik.http.routers.${NAME}-api.entrypoints=websecure
      - traefik.http.routers.${NAME}-api.tls=true
      - traefik.http.services.${NAME}-api.loadbalancer.server.port=4000

  frontend:
    container_name: ${NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_PROXY_TARGET=http://backend:4000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver 
      - traefik.http.routers.${NAME}.entrypoints=websecure
      - traefik.http.routers.${NAME}.tls=true
      - traefik.http.services.${NAME}.loadbalancer.server.port=5173

networks:
  web:
    external: true

  lan:
    name: lan_${NAME}